-- Session #1
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
UPDATE pizzeria SET rating = 5.0 WHERE id = 1;
UPDATE pizzeria SET rating = 5.0 WHERE id = 2;
COMMIT;

-- Session #2
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
UPDATE pizzeria SET rating = 5.0 WHERE id = 2;
UPDATE pizzeria SET rating = 5.0 WHERE id = 1;
COMMIT;
